repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1 # Ruff version.
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.4 # uv version.
    hooks:
      - id: uv-lock
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/allganize/ty-pre-commit
    rev: v0.0.17 # Last Ty version.
    hooks:
      # Run the type checker using Python 3.13 and the virtual environment.
      - id: ty-check
        stages: [manual]
        args: ['--python-version', '3.13', '--python', '.venv']
